### ISSUE TITLE
Please update for Laravel 6 

### ISSUE THREAD

**Issue by larswoltersdev** [sandervanhooft/laravel-payable-redirect-mollie#10]
Can this be updated for Laravel 6? Or are there better ways / packages now? Looking for exactly a solution like this. 

PS: Dear Sander, is it possible to get in touch with you?

**Comment by sandervanhooft** [comment]
I’m traveling this week. Feel free to submit a PR, or wait for Cashier Mollie one-off payment support (ETA 6 weeks).
