### ISSUE TITLE
PaymentUpdated event not emitted

### ISSUE THREAD

**Issue by sten** [sandervanhooft/laravel-payable-redirect-mollie#6]
When Mollie fires the webhook, no PaymentUpdated event is fired. I am not sure we are doing something wrong. Maybe the event is supposed the fire when a database update is made on the Payment model. Because the PaymentUpdated event is not fired, the different event types depending on the payment status are not fired.

## Possible implementation

I have solved the problem by adding a line to the webhook controller:

```
    public function handle(Request $request)
    {
        $payment = Payment::where('gateway_payment_reference', $request->id)->firstOrFail();
        $paymentGateway = new $payment->gateway_name;
        $paymentGateway->fetchUpdateFor($payment);
        event(new PaymentUpdated($payment));
        return response()->json(null, 200);
    }
```

How should the event normally be emitted.

## Your environment

* Laravel 5.6
* PHP 7.2

**Comment by sandervanhooft** [comment]
Hi @sten,

Are you by any chance testing with `Event::fake()` and `Event::assertDispatched(...)`?

**Comment by sandervanhooft** [comment]
The PaymentUpdate event should be triggered from [here in the Payment model](https://github.com/sandervanhooft/laravel-payable-redirect-mollie/blob/fbb04b97bdf385589059e965892fc1fc522a4d38/src/Payment.php#L22:L25) (after the model payment record is updated).

**Comment by sten** [comment]
@sandervanhooft Thanks for checking this! We were not using `Event::fake()` nor `Event::assertDispatched()`. But indeed, the event should be triggered after the payment record is updated. We will check it again and if it still does not work, we'll just keep our dirtier fix.

**Comment by sandervanhooft** [comment]
@sten Great it worked out!

This way the event is triggered only when the model record values _really_ have been modified.

So it is not triggered if the payment status has not been updated.
